In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Player': ['Anand', 'Anand', 'Vidit', 'Vidit', 'Anand'],
    'Opening': ['Ruy Lopez', 'Sicilian', 'Ruy Lopez', 'French', 'Sicilian'],
    'Accuracy': [92, 88, 85, 90, 95],
    'Moves': [45, 30, 50, 40, 60]
}

df= pd.DataFrame(data)

In [3]:
df

  Player    Opening  Accuracy  Moves
0  Anand  Ruy Lopez        92     45
1  Anand   Sicilian        88     30
2  Vidit  Ruy Lopez        85     50
3  Vidit     French        90     40
4  Anand   Sicilian        95     60

In [5]:
# Basic Grouping (Ek column par):
# Mujhe dekhna hai ki har player ki overall average (mean) accuracy kya hai:

avg_accuracy = df.groupby("Player")["Accuracy"].mean()
avg_accuracy

Player
Anand    91.666667
Vidit    87.500000
Name: Accuracy, dtype: float64

In [8]:
# Advanced Grouping (Multiple calculations ek saath):
# Agar mujhe har player ka average accuracy BHI chahiye, aur total moves BHI chahiye, 
# toh hum .agg() (aggregation) function ka use karte hain.

adv_group = df.groupby("Player").agg({
    "Accuracy":"mean",
    "Moves":"sum"
})
print(adv_group)

         Accuracy  Moves
Player
Anand   91.666667    135
Vidit   87.500000     90

In [9]:
# DataFrame 1: Employees
emp_data = {
    'emp_id': [101, 102, 103],
    'name': ['Rahul', 'Priya', 'Amit']
}
df_emp = pd.DataFrame(emp_data)

In [10]:
# DataFrame 2: Departments
dept_data = {
    'emp_id': [101, 102, 104], # Notice 103 yahan nahi hai, aur 104 wahan nahi hai
    'department': ['Sales', 'IT', 'HR']
}
df_dept = pd.DataFrame(dept_data)

In [11]:
df_emp

   emp_id   name
0     101  Rahul
1     102  Priya
2     103   Amit

In [12]:
df_dept

   emp_id department
0     101      Sales
1     102         IT
2     104         HR

In [13]:
# Example: Humein saare employees chahiye, bhale hi unka department na mila ho:

result = pd.merge(df_emp, df_dept, on="emp_id", how="left")
result

   emp_id   name department
0     101  Rahul      Sales
1     102  Priya         IT
2     103   Amit        NaN

In [16]:
# DataFrame 1: January ka data
df_jan = pd.DataFrame({
    'Order_ID': [1, 2],
    'Amount': [500, 700]
})
df_jan

   Order_ID  Amount
0         1     500
1         2     700

In [17]:
# DataFrame 2: February ka data
df_feb = pd.DataFrame({
    'Order_ID': [3, 4],
    'Amount': [600, 800]
})
df_feb

   Order_ID  Amount
0         3     600
1         4     800

In [18]:
combined_df = pd.concat([df_jan,df_feb], ignore_index=True)
print(combined_df)

   Order_ID  Amount
0         1     500
1         2     700
2         3     600
3         4     800

In [ ]:
# 1. GroupBy & Aggregation (Level 1)
# Task: Region ke hisaab se total sales, aur Salesperson_Name ke hisaab se total sales aur average units nikalna.

# Q1: Single aggregation
result = df.groupby("Region")["Sales_Amount"].sum()

# Q2: Multiple aggregations
result2 = df.groupby("Salesperson_Name").agg({
    "Sales_Amount": "sum",
    "Units_Sold": "mean"
})

# 2. Merge / Join (Level 2)
# Task: orders_df ka saara data rakhna (Left Join) aur customers_df se matching customer_id par merge karna.

final_df = pd.merge(orders_df, customers_df, on="customer_id", how="left")

# 3. Concat / Stacking (Level 3)
# Task: North aur South India ki sales tables ko ek ke neeche ek stack karna aur index reset karna.

all_india_sales = pd.concat([north_zone_sales, south_zone_sales], ignore_index=True)