In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Match_ID": [101, 102, 103, 104],
    "Opening": ["Ruy Lopez", "Sicilian", "French", "King's Indian"],
    "Moves": [45, 32, 50, 28],
    "Result": ["Win", "Draw", "Loss", "Win"]
}
df = pd.DataFrame(data)

In [3]:
df

   Match_ID        Opening  Moves Result
0       101      Ruy Lopez     45    Win
1       102       Sicilian     32   Draw
2       103         French     50   Loss
3       104  King's Indian     28    Win

In [4]:
df.head(2)

   Match_ID    Opening  Moves Result
0       101  Ruy Lopez     45    Win
1       102   Sicilian     32   Draw

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Match_ID  4 non-null      int64
 1   Opening   4 non-null      str
 2   Moves     4 non-null      int64
 3   Result    4 non-null      str
dtypes: int64(2), str(2)
memory usage: 260.0 bytes

In [6]:
df.describe()

         Match_ID      Moves
count    4.000000   4.000000
mean   102.500000  38.750000
std      1.290994  10.436315
min    101.000000  28.000000
25%    101.750000  31.000000
50%    102.500000  38.500000
75%    103.250000  46.250000
max    104.000000  50.000000

In [9]:
wins_record = df[df['Result']=='Win']
wins_record

   Match_ID        Opening  Moves Result
0       101      Ruy Lopez     45    Win
3       104  King's Indian     28    Win

In [12]:
wins_record = df[(df['Result']=='Win') & (df['Moves'] > 40)]
wins_record

   Match_ID    Opening  Moves Result
0       101  Ruy Lopez     45    Win